[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
axum = "0.5.16"
hyper = { version = "0.14.20", features = ["full"] }
tokio = { version = "1.21.2", features = ["full"] }

[dev-dependencies]
reqwest = "0.11.12"
